##### Pre-filetring:
## MinDistDataPointsFilter:
# Keep points which lie beyond a radial threshold in meters.
## SurfaceNormalDataPointsFilter:
# The surface normal to each point is estimated by finding knn neighboring points (including the point itself) and taking the eigen-# vector corresponding to the smallest eigen-value of all neighboring points.
## MaxDensityDataPointsFilter:
# Sub-sampling occurs mostly in high density regions. The result is a cloud with lower density overall with the low density regions # being preserved. The param is the desired maximum density of points/m^3.
# https://libpointmatcher.readthedocs.io/en/latest/ICPIntro/

readingDataPointsFilters:
  #- MinDistDataPointsFilter:
  #    minDist: 2
  #- SurfaceNormalDataPointsFilter:
  #      knn: 20
  #      keepDensities: 1
  #- MaxDensityDataPointsFilter:
  #     maxDensity: 1000

referenceDataPointsFilters:
  #- MinDistDataPointsFilter:
  #    minDist: 0.5
  #- SurfaceNormalDataPointsFilter:
  #      knn: 20
  #      keepDensities: 1
  #- MaxDensityDataPointsFilter:
  #     maxDensity: 1000

matcher:
  KDTreeMatcher:
    knn: 3
    maxDist: 0.5
    epsilon: 1
    #3.16
    #maxDist: 0.25

outlierFilters:
  #- MaxDistOutlierFilter:
  #   maxDist: 0.15
  #- SurfaceNormalOutlierFilter:
  #    maxAngle: 1.57 # reject point matches if normals are >90 deg diff
  - TrimmedDistOutlierFilter:
      ratio: 0.90


errorMinimizer:
  PointToPlaneErrorMinimizer

transformationCheckers:
  - CounterTransformationChecker:
      # was 20
      maxIterationCount: 80
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 3

inspector:
  NullInspector

logger:
#  FileLogger
  NullLogger

